apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-api
        image: moeyahya/fraud-detection-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MODEL_PATH
          value: "/app/models/fraud_model.joblib"
        volumeMounts:
        - mountPath: /app/models
          name: models-volume
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: models-volume
        emptyDir: {}