apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
spec:
  type: NodePort  # For local access
  selector:
    app: fraud-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080  # Fixed port for easy access