name: Continuous Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - 'deployments/**'

env:
  DOCKER_IMAGE: moeyahya/fraud-detection-api
  DOCKER_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Kubernetes
      id: setup-kube
      uses: azure/setup-kubectl@v3
      continue-on-error: true

    - name: Deploy to Kubernetes
      if: steps.setup-kube.outcome == 'success' && env.KUBE_CONFIG != ''
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
        if [ -z "$KUBE_CONFIG" ]; then
          echo "No KUBE_CONFIG set, skipping deployment"
          exit 0
        fi
        
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG" > ~/.kube/config
        chmod 600 ~/.kube/config
        
        kubectl apply -f deployments/deployment.yaml
        kubectl apply -f deployments/service.yaml
        
        kubectl rollout status deployment/fraud-detection-api
        kubectl get pods,svc