name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Create sample data
      run: |
        mkdir -p data
        python -c "
        import pandas as pd;
        pd.DataFrame({
            'step': [1, 2, 3, 4, 5],
            'type': ['CASH_IN', 'CASH_OUT', 'PAYMENT', 'TRANSFER', 'DEBIT'],
            'amount': [100, 200, 300, 400, 500],
            'nameOrig': ['A', 'B', 'C', 'D', 'E'],
            'oldbalanceOrg': [1000, 2000, 3000, 4000, 5000],
            'newbalanceOrig': [900, 1900, 2900, 3900, 4900],
            'nameDest': ['X', 'Y', 'Z', 'W', 'V'],
            'oldbalanceDest': [500, 600, 700, 800, 900],
            'newbalanceDest': [600, 700, 800, 900, 1000],
            'isFraud': [0, 1, 0, 1, 0],
            'isFlaggedFraud': [0, 0, 0, 0, 0]
        }).to_csv('data/sample_fraud.csv', index=False)
        "

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov joblib scikit-learn imbalanced-learn pandas

    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE pytest tests/ \
          --cov=src \
          --cov-report=xml \
          --cov-report=term-missing \
          -v

    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.xml
        flags: unittests